spring.application.name=weddingplanner
spring.datasource.url=jdbc:postgresql://localhost:5432/weddingplanner
spring.datasource.username=wedding
spring.datasource.password=wedding

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true